### ISSUE TITLE
empty block ?

### ISSUE THREAD

**Issue by orenyodfat** [daostack/dutchx-bootstrapper-ui#12]
https://github.com/daostack/dutchx-bootstrapper-ui/blob/master/src/organizations/dashboard.ts#L151

**Comment by dkent600** [comment]
this is intended, if an exception is thrown then web3 remains undefined, which is correct.

**Comment by dkent600** [comment]
all the same intentional pattern.

**Comment by orenyodfat** [comment]
what is the login here ? https://github.com/daostack/dutchx-bootstrapper-ui/blob/master/src/resources/customElements/TokenBalance/TokenBalance.ts#L74

**Comment by dkent600** [comment]
> what is the login here

I don't understand, there is no reference to "login"

**Comment by orenyodfat** [comment]
> > what is the login here
> 
> I don't understand, there is no reference to "login"

login = logic :)

**Comment by dkent600** [comment]
If for some reason we can't access the token then we fail gracefully and display "N/A".

**Comment by dkent600** [comment]
these are ok, lint is good
