### ISSUE TITLE
master branch tests failing!

### ISSUE THREAD

**Issue by orenyodfat** [daostack/dutchx-bootstrapper-ui#9]
see https://travis-ci.com/daostack/dutchx-bootstrapper-ui/branches

**Comment by dkent600** [comment]
As described in the PR descriptions and discord messages:  This is fixed in https://github.com/daostack/dutchx-bootstrapper-ui/tree/upgradeToArcRc.3.

Once that is merged, the other branches will be rebased and magically their tests will all pass.

**Comment by orenyodfat** [comment]
It is not merged yet :)
